### ISSUE TITLE
Find new and optimal DICOM library

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/gi-yagit#9]

**Comment by kdbogusz** [comment]
Short list of libraries for reading and writing DICOM files I've checked out so far:

[GDCM](http://gdcm.sourceforge.net/wiki/index.php/Main_Page)
* Last updated May 2021
* Licence seems alright
* Appears to have everything needed

[vega](https://github.com/project-eutopia/vega)
* Last updated March 2019
* MIT licence
* I still can't find, how reading images works in the documentation

[Imebra](https://imebra.com/)
* dead

DCMlite
* Seems to have two versions: [the original](https://github.com/sprinfall/dcm) (last updated January 2020) and a [forked version](https://github.com/feliwir/dcmlite) (last updated March 2019)
* Original has no licence and can't write files, so it's out of the question
* Forked version has MIT licence and a simple writer
* No documentation for either of them

[DCMTK](https://dicom.offis.de/dcmtk.php.en)
* Last updated May 2021
* Does just about everything
* Long documentation, I didn't see anything particularly long
* DICOM reader works differently than Imebra reader, which might make things more difficult

[DicomSDL](https://code.google.com/archive/p/dicomsdl/)
* Last updated 2011

[odil](https://odil.readthedocs.io/en/latest/)
* Last updated January 2021
* Weird French licence, seems fine
* Reader is OK, does enough to work
* I had trouble installing it, but that's probably because of me

[Qt DICOM](http://qtdcm.gforge.inria.fr/)
* Last updated January 2016

**Comment by grzanka** [comment]
Is Imebra really dead ? I agree it is not very active and only single person maintain it:
https://imebra.com/wp-content/uploads/documentation/html/html/changes_log.html
![image](https://user-images.githubusercontent.com/7374733/121056304-5ba22a00-c7be-11eb-874e-c6032a82c925.png)

Looking at this list I'd say that most promising candidates are:
- DCMTK
- odil
- GDCM

**Comment by kdbogusz** [comment]
Well calling it dead is a bit of an exaggeration, but I decided to leave it at that, since we want to move away from it. Personally I find GDCM to be the most promising at the moment.

**Comment by grzanka** [comment]
We finally decided to use GDCM
